---
- hosts: nodes
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Run the app container
      docker_container:
        name: my-python-app
        image: yuro/project-devops-image:latest
        state: started
        ports:
          - "5000:5000"
